---
version: "3.8"

services:
  api:
    image: "${API_IMAGE}"
    working_dir: /src/api
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - ENV=production
      - SECRET_KEY="${SECRET_KEY}"
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - API_URL=${API_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - static_volume:/src/api/staticfiles
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: "${NGINX_IMAGE}"
    build: ../nginx
    volumes:
      - static_volume:/src/api/staticfiles
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
