---
version: "3.8"

services:
  api:
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - ENV=production
    volumes:
      - static_volume:/home/src/api/staticfiles
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ../nginx
    volumes:
      - static_volume:/home/src/web/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
