---
version: "3.8"

services:
  api:
    container_name: competitor-matching-model-api
    image: competitor-matching-model/api:latest
    command: python api/manage.py runserver 0.0.0.0:8000
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      DEBUG: 1
      ENV: development
      FRONTEND_URL: http://localhost:5173
      SECRET_KEY: >
        django-insecure-zohz1_1^*kqz%9y@=r-j3a2a2c4he6v#%r!_rvk0smkykq!t4^
      API_URL: http://localhost:8000
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../:/src

  db:
    container_name: competitor-matching-model-db
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata-api:/var/lib/postgresql/data/

volumes:
  pgdata-api:
