# Generated by Django 5.0.3 on 2024-03-27 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={},
        ),
    ]
