# Generated by Django 5.0.3 on 2024-03-27 22:59

from django.db import migrations


def add_lululemon(apps, schema_editor):
    brand = apps.get_model("brands", "Brand")
    db_alias = schema_editor.connection.alias
    brand.objects.using(db_alias).create(
        name="Lululemon", logo="https://logos-world.net/wp-content/uploads/2020/09/Lululemon-Emblem-700x394.png"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0002_alter_brand_options"),
    ]

    operations = [
        migrations.RunPython(add_lululemon),
    ]
