# Generated by Django 5.0.3 on 2024-03-27 23:00

from django.db import migrations


def add_new_balance(apps, schema_editor):
    brand = apps.get_model("brands", "Brand")
    db_alias = schema_editor.connection.alias
    brand.objects.using(db_alias).create(
        name="New Balance",
        logo="https://logos-world.net/wp-content/uploads/2020/09/New-Balance-Logo-1972-2006-700x394.png",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0003_add_lululemon"),
    ]

    operations = [
        migrations.RunPython(add_new_balance),
    ]
