# Generated by Django 5.0.3 on 2024-03-27 23:00

from django.db import migrations


def add_nike(apps, schema_editor):
    brand = apps.get_model("brands", "Brand")
    db_alias = schema_editor.connection.alias
    brand.objects.using(db_alias).create(
        name="Nike",
        logo="https://logos-world.net/wp-content/uploads/2020/04/Nike-Logo-1971-present-700x394.jpg",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0004_add_new_balance"),
    ]

    operations = [migrations.RunPython(add_nike)]
