# Generated by Django 5.0.3 on 2024-03-27 23:00

from django.db import migrations


def add_puma(apps, schema_editor):
    brand = apps.get_model("brands", "Brand")
    db_alias = schema_editor.connection.alias
    brand.objects.using(db_alias).create(
        name="Puma",
        logo="https://logos-world.net/wp-content/uploads/2020/04/Puma-Logo-700x394.png",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0006_add_north_face"),
    ]

    operations = [migrations.RunPython(add_puma)]
