# Generated by Django 5.0.3 on 2024-03-27 23:01

from django.db import migrations


def add_reebok(apps, schema_editor):
    brand = apps.get_model("brands", "Brand")
    db_alias = schema_editor.connection.alias
    brand.objects.using(db_alias).create(
        name="Reebok",
        logo="https://logos-world.net/wp-content/uploads/2020/04/Reebok-Logo-700x394.png",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0007_add_puma"),
    ]

    operations = [
        migrations.RunPython(add_reebok),
    ]
