# Generated by Django 5.0.3 on 2024-04-07 17:45

from django.db import migrations


def enable_under_armour(apps, schema_editor):
    brand = apps.get_model("brands", "Brand")
    db_alias = schema_editor.connection.alias
    brand.objects.using(db_alias).filter(name="Under Armour").update(enabled=True)


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0012_enable_north_face"),
    ]

    operations = [migrations.RunPython(enable_under_armour)]
