# Generated by Django 5.0.3 on 2024-04-07 17:45

from django.db import migrations


def enable_new_balance(apps, schema_editor):
    brand = apps.get_model("brands", "Brand")
    db_alias = schema_editor.connection.alias
    brand.objects.using(db_alias).filter(name="New Balance").update(enabled=True)


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0013_enable_under_armour"),
    ]

    operations = [migrations.RunPython(enable_new_balance)]
