# Generated by Django 5.0.3 on 2024-03-18 18:13

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                ("pkid", models.BigAutoField(primary_key=True, serialize=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field="id"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BoundingBox",
            fields=[
                ("pkid", models.BigAutoField(primary_key=True, serialize=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
                ),
                ("x", models.DecimalField(decimal_places=7, max_digits=15)),
                ("y", models.DecimalField(decimal_places=7, max_digits=15)),
                ("width", models.DecimalField(decimal_places=7, max_digits=15)),
                ("height", models.DecimalField(decimal_places=7, max_digits=15)),
                ("confidence", models.DecimalField(decimal_places=7, max_digits=15)),
                (
                    "brand",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="brands.brand", to_field="id"
                    ),
                ),
                (
                    "image_analysis",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="images.analysis", to_field="id"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field="id"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("pkid", models.BigAutoField(primary_key=True, serialize=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
                ),
                ("source", models.URLField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field="id"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="analysis",
            name="image",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="images.image", to_field="id"),
        ),
    ]
