# Generated by Django 5.0.3 on 2024-04-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boundingbox",
            name="excluded",
            field=models.BooleanField(default=False),
        ),
    ]
