---
name: Lint and Format Codebase
"on": [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install flake8 isort black

      - name: Lint
        run: |
          make lint

      - name: Format
        run: |
          make format
          if [ $? -ne 0 ]; then
            echo "Code formatting required. Please run `make format`
                  to format the code."
            exit 1
          fi
